### ISSUE TITLE
Dark mode transition does not target before & after pseudo elements

### ISSUE THREAD

**Issue by ghost** [kimmobrunfeldt/blog#8]
Hey! Great blog. I found a little bug when visiting the post [Writing, or coding](https://kimmo.blog/posts/1-writing-or-coding/). When switching between dark/light mode, you'll notice the chat bubbles' pseudo elements do not have the transition effect applied to them. Fortunately, this is a simple fix. In `dark-mode.css`, you can make a change like the following:

```diff
- .loaded, .loaded * {
+ .loaded, .loaded *, .loaded *::before, .loaded *::after {
  transition: box-shadow 500ms ease, background-color 500ms ease, border-color 500ms ease;
}
```

**Comment by kimmobrunfeldt** [comment]
Thanks, fixed this now!
